ALTER TABLE SISESMER.BCO02
 DROP PRIMARY KEY CASCADE;
DROP TABLE SISESMER.BCO02 CASCADE CONSTRAINTS;

CREATE TABLE SISESMER.BCO02
(
  BCO02CODI  NUMBER                             NOT NULL,
  BCO02DESC  VARCHAR2(250 BYTE)                 NOT NULL,
  BCO02FCRE  DATE                               NOT NULL,
  BCO02LCRE  VARCHAR2(50 BYTE)                  NOT NULL,
  BCO02ESTA  VARCHAR2(2 BYTE)                   NOT NULL,
  BCO02FMOD  DATE,
  BCO02LMOD  VARCHAR2(50 BYTE)
)
TABLESPACE TSD_INTEGRADO
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX SISESMER.BCO02_PK ON SISESMER.BCO02
(BCO02CODI)
LOGGING
TABLESPACE TSD_INTEGRADO
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP PUBLIC SYNONYM BCO02;

CREATE PUBLIC SYNONYM BCO02 FOR SISESMER.BCO02;


ALTER TABLE SISESMER.BCO02 ADD (
  CONSTRAINT BCO02_PK
 PRIMARY KEY
 (BCO02CODI)
    USING INDEX 
    TABLESPACE TSD_INTEGRADO
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));
