ALTER TABLE SISESMER.BCO021
 DROP PRIMARY KEY CASCADE;
DROP TABLE SISESMER.BCO021 CASCADE CONSTRAINTS;

CREATE TABLE SISESMER.BCO021
(
  BCO021CODI  NUMBER                            NOT NULL,
  BCO02CODI   NUMBER                            NOT NULL,
  REN21CODI   NUMBER                            NOT NULL,
  BCO021ESTA  VARCHAR2(2 BYTE)                  NOT NULL,
  BCO021FCRE  DATE                              NOT NULL,
  BCO021LCRE  VARCHAR2(50 BYTE)                 NOT NULL
)
TABLESPACE TSD_INTEGRADO
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX SISESMER.BCO021_PK ON SISESMER.BCO021
(BCO021CODI)
LOGGING
TABLESPACE TSD_INTEGRADO
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP PUBLIC SYNONYM BCO021;

CREATE PUBLIC SYNONYM BCO021 FOR SISESMER.BCO021;


ALTER TABLE SISESMER.BCO021 ADD (
  CONSTRAINT BCO021_PK
 PRIMARY KEY
 (BCO021CODI)
    USING INDEX 
    TABLESPACE TSD_INTEGRADO
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));

ALTER TABLE SISESMER.BCO021 ADD (
  CONSTRAINT BCO021_R01 
 FOREIGN KEY (BCO02CODI) 
 REFERENCES SISESMER.BCO02 (BCO02CODI));
