SET DEFINE OFF;
Insert into SISESMER.SINARP_CREDENCIAL
   (ID, IP, USUARIO, PASS, ESTADO)
 Values
   (1, '192.168.130.1', 'buzon-api', '8ac5ff394fadf6a181d03c954af64d9d', 1);
Insert into SISESMER.SINARP_CREDENCIAL
   (ID, IP, USUARIO, PASS, ESTADO)
 Values
   (2, '192.168.130.1', 'cabildo', '91acee0fd9536ccf69e47be6db28e186', 1);
Insert into SISESMER.SINARP_CREDENCIAL
   (ID, IP, USUARIO, PASS, ESTADO)
 Values
   (3, '192.168.130.1', 'test', '8ac5ff394fadf6a181d03c954af64d9d', 1);
Insert into SISESMER.SINARP_CREDENCIAL
   (ID, IP, USUARIO, PASS, ESTADO)
 Values
   (4, '192.168.130.1', 'intranet', '8ac5ff394fadf6a181d03c954af64d9d', 1);
COMMIT;
