


SELECT 'INSERT INTO GEN01(GEN01CODI, GEN02CODI, GEN01RUC, GEN01TID, GEN01APE, GEN01COM, GEN01DIR, GEN01ECIV, GEN01SEX, GEN01LCREA, GEN01FCRE) VALUES(SQ_GEN01.NEXTVAL, '||
       CASE SIGCAL01TPROP 
        WHEN 'PRIVADO' THEN 1
        WHEN '' THEN 1
        WHEN 'P¿¿BLICO' THEN 4
        WHEN 'MUNICIPAL' THEN 5
       END||', '''||GEN01RUC||''','||GEN01TID||', '''||GEN01COM||''', '''||GEN01COM||''', '''
       ||(SELECT MAX(GEN01DIR) FROM SIGCAL01 B WHERE B.GEN01RUC = A.GEN01RUC)||''',''S'',''N'',''SISESMER'', SYSDATE);' 
FROM SIGCAL01 A
WHERE GEN01RUC NOT IN (SELECT GEN01RUC FROM GEN01)
GROUP BY GEN01RUC, GEN01COM, GEN01TID, SIGCAL01TPROP