SELECT (SELECT E.SEG01DESCRIPCION FROM ST_SEGINT E WHERE E.SEG01SISTEMA = C.SEG01SISTEMA ) MODULO,
    C.S01CODI COD_SISTEMA, D.SEG01DES OPCION, 
    A.SEG03CODI, A.SEG03CODNOMI, B.NOM01CEDUAL, B.NOM01APELLIDOS || ' ' || B.NOM01NOMBRES FUNCIONARIO,
    B.NOM01FINGRESO FECHA_INGRESO_GADMCE, B.NOM01FSALIDA, B.NOM01RRDIRE DIRECCION, B.NOM01RTELE TELEFONO, 
    DECODE(C.SEG02ACC, 'T', 'ACCESO TOTAL','C', 'SOLO CONSULTA') TIPO_ACCESO,
    (SELECT SEG04NOM  FROM ST_SEG04 H WHERE H.SEG04CODI = B.SEG04CODI) DIR_ADMIN,
    (SELECT SEG05DESC FROM ST_SEG05 G WHERE G.SEG05CODI = E.SEG05CODI ) DENOMINACION
FROM ST_SEG03 A, NOM01 B, ST_SEG02 C, ST_SEG01 D, CAR09 E
WHERE A.SEG03CODNOMI = B.NOM01CODI
      AND A.SEG03CODI = C.SEG03CODI
      AND C.S01CODI = D.S01CODI
      AND E.NOM01CODI = B.NOM01CODI
      --AND C.SEG01SISTEMA = 'AVALUOS'
      AND E.CAR09FINI >= TO_DATE('1-01-2014','DD-MM-RRRR')
      AND E.CAR09FINI <= TO_DATE('31-07-2018','DD-MM-RRRR')
ORDER BY C.SEG01SISTEMA, SEG03CODNOMI, COD_SISTEMA