SELECT * FROM REN581


SELECT REN05CODI, GEN01CODI, PK_UTI.GEN01_COM(GEN01CODI) CONTRIBUYENTE,
       REN05CODZONA, CASE PK_UTI.TITULO_CATALOGOS(91,REN05CODZONA)
                       WHEN 'RE-00600' THEN 'NO REGISTRA'
                       ELSE PK_UTI.TITULO_CATALOGOS(91,REN05CODZONA)
                     END ZONA,
       REN21CODB,    CASE PK_UTI.TITULO_CATALOGOS(7,REN21CODB)
                       WHEN 'RE-00600' THEN 'NO REGISTRA'
                       ELSE PK_UTI.TITULO_CATALOGOS(7,REN21CODB)
                     END PARROQUIA,
       REN21CODE,    CASE PK_UTI.TITULO_CATALOGOS(133,REN21CODE)
                       WHEN 'RE-00600' THEN 'NO REGISTRA'
                       ELSE PK_UTI.TITULO_CATALOGOS(133,REN21CODE)
                     END BARRIO,
       REN21CODG,    CASE PK_UTI.TITULO_CATALOGOS(135,REN21CODG)
                       WHEN 'RE-00600' THEN 'NO REGISTRA'
                       ELSE PK_UTI.TITULO_CATALOGOS(135,REN21CODG)
                     END NATURALEZA_ACTIVIDAD,
       REN21CODF,    CASE PK_UTI.TITULO_CATALOGOS(134,REN21CODF)
                       WHEN 'RE-00600' THEN 'NO REGISTRA'
                       ELSE PK_UTI.TITULO_CATALOGOS(134,REN21CODF)
                     END TIPO_ACTIVIDAD,
       CASE NVL(LENGTH(REN05LMOD),0)
        WHEN 0 THEN REN05LCRE||' CREA'
        ELSE REN05LMOD||' MODIFICA'
       END ULTIMA_MODIFICACION,
       CASE NVL(LENGTH(REN05FMOD),0)
        WHEN 0 THEN REN05FCRE
        ELSE REN05FMOD
       END FECHA_ULT_MODIF,
       REN05ESTA
FROM REN05
WHERE REN05ESTA IN ('IG', 'MD')
ORDER BY REN05CODZONA ASC


SELECT * FROM REN21 WHERE REN21CODI IN (SELECT DISTINCT(REN21CODF) FROM REN05)



select * from st_seg03 where seg03codi = 'AGRACIA'