CREATE OR REPLACE TRIGGER "SISESMER".t_sysNOM06
 AFTER
   DELETE OR UPDATE OF 
    NOM06CODI,
    NOM01CODI,
    SEG20CODI,
    NOM06ESTA,
    NOM06FINI,
    NOM06FFIN,
    NOM06LCRE,
    NOM06FCRE,
    NOM06LMOD,
    NOM06FMOD
 ON NOM06
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
DECLARE
V_SentenciaDML VARCHAR2(20) := NULL;
V_Tabla        VARCHAR2(20) := 'NOM06';
V_Campo        VARCHAR2(20) := NULL;
V_ValorAntes   VARCHAR2(50) := NULL;
V_ValorDespues VARCHAR2(50) := NULL;

BEGIN
    IF updating THEN
       V_SentenciaDML := 'UPDATE';
    ELSIF deleting THEN
       V_SentenciaDML := 'BORRADO';
    END IF;
    
    PK_CTRLTAB8.Insertar(V_Tabla,'NOM06CODI ('||:OLD.NOM01CODI||')',:OLD.NOM06CODI, :NEW.NOM06CODI,V_SentenciaDML);
    PK_CTRLTAB8.Insertar(V_Tabla,'NOM01CODI ('||:OLD.NOM01CODI||')',:OLD.NOM01CODI, :NEW.NOM01CODI,V_SentenciaDML);
    PK_CTRLTAB8.Insertar(V_Tabla,'SEG20CODI ('||:OLD.NOM01CODI||')',:OLD.SEG20CODI, :NEW.SEG20CODI,V_SentenciaDML);
    PK_CTRLTAB8.Insertar(V_Tabla,'NOM06ESTA ('||:OLD.NOM01CODI||')',:OLD.NOM06ESTA, :NEW.NOM06ESTA,V_SentenciaDML);
    PK_CTRLTAB8.Insertar(V_Tabla,'NOM06FINI ('||:OLD.NOM01CODI||')',:OLD.NOM06FINI, :NEW.NOM06FINI,V_SentenciaDML);
    PK_CTRLTAB8.Insertar(V_Tabla,'NOM06FFIN ('||:OLD.NOM01CODI||')',:OLD.NOM06FFIN, :NEW.NOM06FFIN,V_SentenciaDML);
    PK_CTRLTAB8.Insertar(V_Tabla,'NOM06LCRE ('||:OLD.NOM01CODI||')',:OLD.NOM06LCRE, :NEW.NOM06LCRE,V_SentenciaDML);
    PK_CTRLTAB8.Insertar(V_Tabla,'NOM06FCRE ('||:OLD.NOM01CODI||')',:OLD.NOM06FCRE, :NEW.NOM06FCRE,V_SentenciaDML);
    PK_CTRLTAB8.Insertar(V_Tabla,'NOM06LMOD ('||:OLD.NOM01CODI||')',:OLD.NOM06LMOD, :NEW.NOM06LMOD,V_SentenciaDML);
    PK_CTRLTAB8.Insertar(V_Tabla,'NOM06FMOD ('||:OLD.NOM01CODI||')',:OLD.NOM06FMOD, :NEW.NOM06FMOD,V_SentenciaDML);

    EXCEPTION
      WHEN OTHERS THEN
          NULL;
END;
/

