CREATE OR REPLACE TRIGGER "SISESMER".t_sysASI02
 AFTER
   DELETE OR UPDATE OF 
    ASI02CODI,
    ASI01CODI,
    ASI02FECHA,
    ASI02ENTRA,
    ASI02SALIDA,
    ASI02ENTRA2,
    ASI02SALIDA02,
    ASI02REGISTRO,
    HORA_ENTRA1,
    MIN_ENTRA1,
    HORA_SALE1,
    MIN_SALE1,
    HORA_ENTRA2,
    MIN_ENTRA2,
    HORA_SALE2,
    MIN_SALE2,
    HORA_NOCTURNA,
    MIN_NOCTURNA,
    FALTAS,
    PER01CODI,
    NOM01CODI,
    ASI02LCRE,
    ASI02FCRE,
    ASI02LMOD,
    ASI02FMOD
 ON ASI02
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
DECLARE
V_SentenciaDML VARCHAR2(20) := NULL;
V_Tabla        VARCHAR2(20) := 'ASI02';
V_Campo        VARCHAR2(20) := NULL;
V_ValorAntes   VARCHAR2(50) := NULL;
V_ValorDespues VARCHAR2(50) := NULL;

BEGIN
    IF updating THEN
       V_SentenciaDML := 'UPDATE';
    ELSIF deleting THEN
       V_SentenciaDML := 'BORRADO';
    END IF;
    
    PK_CTRLTAB8.Insertar(V_Tabla,'ASI02CODI ('||:OLD.NOM01CODI||')',:OLD.ASI02CODI, :NEW.ASI02CODI,V_SentenciaDML);
    PK_CTRLTAB8.Insertar(V_Tabla,'ASI01CODI ('||:OLD.NOM01CODI||')',:OLD.ASI01CODI, :NEW.ASI01CODI,V_SentenciaDML);
    PK_CTRLTAB8.Insertar(V_Tabla,'ASI02FECHA ('||:OLD.NOM01CODI||')',:OLD.ASI02FECHA, :NEW.ASI02FECHA,V_SentenciaDML);
    PK_CTRLTAB8.Insertar(V_Tabla,'ASI02ENTRA ('||:OLD.NOM01CODI||')',:OLD.ASI02ENTRA, :NEW.ASI02ENTRA,V_SentenciaDML);
    PK_CTRLTAB8.Insertar(V_Tabla,'ASI02SALIDA ('||:OLD.NOM01CODI||')',:OLD.ASI02SALIDA, :NEW.ASI02SALIDA,V_SentenciaDML);
    PK_CTRLTAB8.Insertar(V_Tabla,'ASI02ENTRA2 ('||:OLD.NOM01CODI||')',:OLD.ASI02ENTRA2, :NEW.ASI02ENTRA2,V_SentenciaDML);
    PK_CTRLTAB8.Insertar(V_Tabla,'ASI02SALIDA02 ('||:OLD.NOM01CODI||')',:OLD.ASI02SALIDA02, :NEW.ASI02SALIDA02,V_SentenciaDML);
    PK_CTRLTAB8.Insertar(V_Tabla,'ASI02REGISTRO ('||:OLD.NOM01CODI||')',:OLD.ASI02REGISTRO, :NEW.ASI02REGISTRO,V_SentenciaDML);
    PK_CTRLTAB8.Insertar(V_Tabla,'HORA_ENTRA1 ('||:OLD.NOM01CODI||')',:OLD.HORA_ENTRA1, :NEW.HORA_ENTRA1,V_SentenciaDML);
    PK_CTRLTAB8.Insertar(V_Tabla,'MIN_ENTRA1 ('||:OLD.NOM01CODI||')',:OLD.MIN_ENTRA1, :NEW.MIN_ENTRA1,V_SentenciaDML);
    PK_CTRLTAB8.Insertar(V_Tabla,'HORA_SALE1 ('||:OLD.NOM01CODI||')',:OLD.HORA_SALE1, :NEW.HORA_SALE1,V_SentenciaDML);
    PK_CTRLTAB8.Insertar(V_Tabla,'MIN_SALE1 ('||:OLD.NOM01CODI||')',:OLD.MIN_SALE1, :NEW.MIN_SALE1,V_SentenciaDML);
    PK_CTRLTAB8.Insertar(V_Tabla,'HORA_ENTRA2 ('||:OLD.NOM01CODI||')',:OLD.HORA_ENTRA2, :NEW.HORA_ENTRA2,V_SentenciaDML);
    PK_CTRLTAB8.Insertar(V_Tabla,'MIN_ENTRA2 ('||:OLD.NOM01CODI||')',:OLD.MIN_ENTRA2, :NEW.MIN_ENTRA2,V_SentenciaDML);
    PK_CTRLTAB8.Insertar(V_Tabla,'HORA_SALE2 ('||:OLD.NOM01CODI||')',:OLD.HORA_SALE2, :NEW.HORA_SALE2,V_SentenciaDML);
    PK_CTRLTAB8.Insertar(V_Tabla,'MIN_SALE2 ('||:OLD.NOM01CODI||')',:OLD.MIN_SALE2, :NEW.MIN_SALE2,V_SentenciaDML);
    PK_CTRLTAB8.Insertar(V_Tabla,'HORA_NOCTURNA ('||:OLD.NOM01CODI||')',:OLD.HORA_NOCTURNA, :NEW.HORA_NOCTURNA,V_SentenciaDML);
    PK_CTRLTAB8.Insertar(V_Tabla,'MIN_NOCTURNA ('||:OLD.NOM01CODI||')',:OLD.MIN_NOCTURNA, :NEW.MIN_NOCTURNA,V_SentenciaDML);
    PK_CTRLTAB8.Insertar(V_Tabla,'FALTAS ('||:OLD.NOM01CODI||')',:OLD.FALTAS, :NEW.FALTAS,V_SentenciaDML);
    PK_CTRLTAB8.Insertar(V_Tabla,'PER01CODI ('||:OLD.NOM01CODI||')',:OLD.PER01CODI, :NEW.PER01CODI,V_SentenciaDML);
    PK_CTRLTAB8.Insertar(V_Tabla,'NOM01CODI ('||:OLD.NOM01CODI||')',:OLD.NOM01CODI, :NEW.NOM01CODI,V_SentenciaDML);
    PK_CTRLTAB8.Insertar(V_Tabla,'ASI02LCRE ('||:OLD.NOM01CODI||')',:OLD.ASI02LCRE, :NEW.ASI02LCRE,V_SentenciaDML);
    PK_CTRLTAB8.Insertar(V_Tabla,'ASI02FCRE ('||:OLD.NOM01CODI||')',:OLD.ASI02FCRE, :NEW.ASI02FCRE,V_SentenciaDML);
    PK_CTRLTAB8.Insertar(V_Tabla,'ASI02LMOD ('||:OLD.NOM01CODI||')',:OLD.ASI02LMOD, :NEW.ASI02LMOD,V_SentenciaDML);
    PK_CTRLTAB8.Insertar(V_Tabla,'ASI02FMOD ('||:OLD.NOM01CODI||')',:OLD.ASI02FMOD, :NEW.ASI02FMOD,V_SentenciaDML);

    EXCEPTION
      WHEN OTHERS THEN
          NULL;
END;
/

