CREATE OR REPLACE TRIGGER "SISESMER".t_sysNOM05
 AFTER
   DELETE OR UPDATE OF 
    NOM01CODI,
    NOM05DOCUMENTO,
    NOM05FECHA,
    NOM05USUARIO,
    NOM05DETALLE,
    NOM05CODI
 ON NOM05
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
DECLARE
V_SentenciaDML VARCHAR2(20) := NULL;
V_Tabla        VARCHAR2(20) := 'NOM05';
V_Campo        VARCHAR2(20) := NULL;
V_ValorAntes   VARCHAR2(50) := NULL;
V_ValorDespues VARCHAR2(50) := NULL;

BEGIN
    IF updating THEN
       V_SentenciaDML := 'UPDATE';
    ELSIF deleting THEN
       V_SentenciaDML := 'BORRADO';
    END IF;
    
    PK_CTRLTAB8.Insertar(V_Tabla,'NOM01CODI ('||:OLD.NOM01CODI||')',:OLD.NOM01CODI, :NEW.NOM01CODI,V_SentenciaDML);
    PK_CTRLTAB8.Insertar(V_Tabla,'NOM05DOCUMENTO ('||:OLD.NOM01CODI||')',:OLD.NOM05DOCUMENTO, :NEW.NOM05DOCUMENTO,V_SentenciaDML);
    PK_CTRLTAB8.Insertar(V_Tabla,'NOM05FECHA ('||:OLD.NOM01CODI||')',:OLD.NOM05FECHA, :NEW.NOM05FECHA,V_SentenciaDML);
    PK_CTRLTAB8.Insertar(V_Tabla,'NOM05USUARIO ('||:OLD.NOM01CODI||')',:OLD.NOM05USUARIO, :NEW.NOM05USUARIO,V_SentenciaDML);
    PK_CTRLTAB8.Insertar(V_Tabla,'NOM05DETALLE ('||:OLD.NOM01CODI||')',:OLD.NOM05DETALLE, :NEW.NOM05DETALLE,V_SentenciaDML);
    PK_CTRLTAB8.Insertar(V_Tabla,'NOM05CODI ('||:OLD.NOM01CODI||')',:OLD.NOM05CODI, :NEW.NOM05CODI,V_SentenciaDML);

    EXCEPTION
      WHEN OTHERS THEN
          NULL;
END;
/

